default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsapi_development
  username: kelynnjeri
  password: kelynnjeri
  host: localhost
  port: 5432

test:
  <<: *default
  database: railsapi_test
  username: kelynnjeri
  password: kelynnjeri
  host: localhost
  port: 5432

production:
  <<: *default
  database: railsapi_production
  username: kelynnjeri
  password: kelynnjeri
  host: localhost
  port: 5432

